version: "2.2"

services:
  mysql:
    image: "mysql:8.0.32"
    container_name: tiktok_demo_mysql_8.0.32
    volumes:
      - $HOME/tiktokCache/mysql/datadir:/var/lib/mysql
      - $HOME/tiktokCache/mysql/conf:/etc/mysql/conf.d
      - $HOME/tiktokCache/mysql/logs:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=tiktok_demo
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - CONTAINER_TIMEZONE=Asia/Shanghai
  minio:
    image: "minio/minio:RELEASE.2022-01-04T07-41-07Z"
    container_name: tiktok_demo_minio_20220104
    volumes:
      - $HOME/tiktokCache/minio/data:/data
      - $HOME/tiktokCache/minio/config:/root/.minio
    ports:
      - "9000:9000" # api port
      - "9001:9001" # control port
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=123123123
    command: minio server /data --console-address ":9001" --address ":9000"
  redis:
    image: "redis:6.0"
    container_name: tiktok_demo_redis_6.0
    volumes:
      - $HOME/tiktokCache/redis/datadir:/data
      - $HOME/tiktokCache/redis/conf/redis.conf:/etc/redis/redis.conf
      - $HOME/tiktokCache/redis/logs:/logs
    ports:
      - "6379:6379"
    environment:
      - TZ="Asia/Shanghai"
    command: "redis-server /etc/redis/redis.conf"
  rabbitmq:
    image: "rabbitmq:3.9.13-management"
    container_name: tiktok_demo_rabbitmq_3913m
    hostname: rabbitmq_host
    volumes:
      - $HOME/tiktokCache/rabbitMQ/data:/var/lib/rabbitmq
      - $HOME/tiktokCache/rabbitMQ/log:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: tiktok
      RABBITMQ_DEFAULT_PASS: tiktok

  tiktok_demo:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./wait-for-it.sh:/root/wait-for-it.sh
      - ./config/config.yaml:/root/config/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - minio
      - redis
      - rabbitmq