version: "2.2"

services:
  mysql:
    image: "mysql:8.0.32"
    container_name: tiktok_demo_mysql_8.0.32
    volumes:
      - $HOME/tiktokCache/mysql/datadir:/var/lib/mysql
      - $HOME/tiktokCache/mysql/conf:/etc/mysql/conf.d
      - $HOME/tiktokCache/mysql/logs:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=tiktok_demo
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=root
      - CONTAINER_TIMEZONE=Asia/Shanghai
  minio:
    image: 'minio/minio:RELEASE.2022-01-04T07-41-07Z'
    container_name: tiktok_demo_20220104
    volumes:
      - $HOME/tiktokCache/minio/data:/data
      - $HOME/tiktokCache/minio/config:/root/.minio
    ports:
      - "9000:9000" # api port
      - "9001:9001" # control port
    environment:
      - MINIO_ROOT_USER=tiktokDemo
      - MINIO_ROOT_PASSWORD=tiktokDemo@123456
    command: minio server /data --console-address ":9001" --address ":9000"
  tiktok_demo:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./wait-for-it.sh:/apps/wait-for-it.sh
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306","--", "/apps/tiktok_demo" ]