ip:
  host: &host 127.0.0.1
jwt:
  secret: tiktok_demo
mysql:
  host: *host
  port: 3306
  database: tiktok_demo
  username: root
  password: 123456
OneDayOfHours:
  OneDayOfHours: 60 * 60 * 24
  OneMinute: 60 * 1
  OneMonth: 60 * 60 * 24 * 30
  OneYear: 365 * 60 * 60 * 24
redis:
  host: *host
  port: 6379
  # password: 123456