ip:
  host: &host 192.168.254.129
jwt:
  secret: tiktok_demo
mysql:
  host: *host
  port: 3306
  database: tiktok_demo
  username: user
  password: 123456
OneDayOfHours:
  OneMinute: 60
  OneDayOfHours: 86400
  OneMonth: 2592000
  OneYear: 946080000
minio:
  host: *host
  port: 9000
  rootUser: minio
  rootPassword: 123123123
  videoBuckets: video
  picBuckets: pic
rabbitMQ:
  host: *host
  port: 5673
  defaultUser: guest
  defaultPass: guest
redis:
  host: *host
  port: 6379
  password: 123456