jwt:
  secret: tiktok_demo
mysql:
  host: 192.168.254.129
  port: 3306
  database: tiktok_demo
  username: user
  password: 123456
OneDayOfHours:
  OneMinute: 60
  OneDayOfHours: 86400
  OneMonth: 2592000
  OneYear: 946080000