jwt:
  secret: tiktok_demo
mysql:
  host: 192.168.254.129
  port: 3306
  database: tiktok_demo
  username: user
  password: 123456
OneDayOfHours:
  OneDayOfHours: 60 * 60 * 24
  OneMinute: 60 * 1
  OneMonth: 60 * 60 * 24 * 30
  OneYear: 365 * 60 * 60 * 24